apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grappl-data
  namespace: grappl
  labels:
    app: grappl
    managed-by: manual
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
