FROM cgr.dev/chainguard/nginx:latest

COPY ui/index.html /usr/share/nginx/html/index.html
COPY ui/app.js /usr/share/nginx/html/app.js
COPY ui/styles.css /usr/share/nginx/html/styles.css
COPY ui/nginx.conf /etc/nginx/conf.d/default.conf
